apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Build .NET Core App
on:
  push:
    branches:
      - main
jobs:
  build:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Checkout repository
      - uses: actions/setup-dotnet@v
        name: Install .NET Core SDK
      - uses: actions/dotnet/build@v2
        name: Build application
        with:
          project: MyApp.csproj
          arguments: --configuration Release
      - uses: actions/dotnet/test@v2
        name: Run unit tests
        with:
          project: MyApp.csproj
          arguments: --configuration Release
      - uses: actions/upload-artifacts@v2
        name: Archive artifacts
        with:
          name: artifacts
          path: bin/Release/net6.0
