apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Build .NET Core App

on:
  push:
    branches:
      - main

jobs:
  build:
    steps:
      - name: Checkout repository
        uses: cloudbees-io/checkout@v1

      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.0

      - name: Build application
        uses: actions/dotnet/build@v2
        with:
          project: MyApp.csproj
          arguments: --configuration Release

      - name: Run unit tests
        uses: actions/dotnet/test@v2
        with:
          project: MyApp.csproj
          arguments: --configuration Release

      - name: Archive artifacts
        uses: actions/upload-artifacts@v2
        with:
          name: artifacts
          path: bin/Release/net6.0